"""initial_schema

Revision ID: e94763d0a095
Revises: 
Create Date: 2026-09-10 20:31:55.583866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94763d0a095'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.Column('company_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('india_eligibility', sa.Enum('LIKELY', 'UNCLEAR', 'UNLIKELY', name='indiaeligibility'), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'UNKNOWN', name='employmenttype'), nullable=False),
    sa.Column('internship_type', sa.Enum('SUMMER', 'WINTER', 'GENERAL', 'UNKNOWN', name='internshiptype'), nullable=False),
    sa.Column('compensation_type', sa.Enum('PAID', 'UNPAID', 'UNKNOWN', name='compensationtype'), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('salary_period', sa.String(length=32), nullable=True),
    sa.Column('experience_min', sa.Float(), nullable=True),
    sa.Column('experience_max', sa.Float(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_internship_fingerprint')
    )
    op.create_index(op.f('ix_internships_company_name'), 'internships', ['company_name'], unique=False)
    op.create_index(op.f('ix_internships_compensation_type'), 'internships', ['compensation_type'], unique=False)
    op.create_index(op.f('ix_internships_deadline'), 'internships', ['deadline'], unique=False)
    op.create_index('ix_internships_eligibility_active', 'internships', ['india_eligibility', 'is_active'], unique=False)
    op.create_index(op.f('ix_internships_employment_type'), 'internships', ['employment_type'], unique=False)
    op.create_index(op.f('ix_internships_fingerprint'), 'internships', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_internships_id'), 'internships', ['id'], unique=False)
    op.create_index(op.f('ix_internships_india_eligibility'), 'internships', ['india_eligibility'], unique=False)
    op.create_index(op.f('ix_internships_internship_type'), 'internships', ['internship_type'], unique=False)
    op.create_index(op.f('ix_internships_is_active'), 'internships', ['is_active'], unique=False)
    op.create_index(op.f('ix_internships_is_seed'), 'internships', ['is_seed'], unique=False)
    op.create_index(op.f('ix_internships_posted_at'), 'internships', ['posted_at'], unique=False)
    op.create_index('ix_internships_posted_at_active', 'internships', ['posted_at', 'is_active'], unique=False)
    op.create_index(op.f('ix_internships_remote'), 'internships', ['remote'], unique=False)
    op.create_index(op.f('ix_internships_title'), 'internships', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internships_title'), table_name='internships')
    op.drop_index(op.f('ix_internships_remote'), table_name='internships')
    op.drop_index('ix_internships_posted_at_active', table_name='internships')
    op.drop_index(op.f('ix_internships_posted_at'), table_name='internships')
    op.drop_index(op.f('ix_internships_is_seed'), table_name='internships')
    op.drop_index(op.f('ix_internships_is_active'), table_name='internships')
    op.drop_index(op.f('ix_internships_internship_type'), table_name='internships')
    op.drop_index(op.f('ix_internships_india_eligibility'), table_name='internships')
    op.drop_index(op.f('ix_internships_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_fingerprint'), table_name='internships')
    op.drop_index(op.f('ix_internships_employment_type'), table_name='internships')
    op.drop_index('ix_internships_eligibility_active', table_name='internships')
    op.drop_index(op.f('ix_internships_deadline'), table_name='internships')
    op.drop_index(op.f('ix_internships_compensation_type'), table_name='internships')
    op.drop_index(op.f('ix_internships_company_name'), table_name='internships')
    op.drop_table('internships')
    # ### end Alembic commands ###
